<?php

namespace Database\Seeders;

use App\Models\Movie;
use Illuminate\Database\Seeder;

class DefaultMovieSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->movies() as $movie) {
            Movie::query()->firstOrCreate(
                ['slug' => $movie['slug']],
                $movie
            );
        }
    }

    private function movies(): array
    {
        return [
            [
                'slug' => 'phi-phong-quy-mau-rung-thieng',
                'section' => 'now-showing',
                'title' => 'Phí Phông: Quỷ Máu Rừng Thiêng',
                'genre' => 'Kinh dị, Giật gân',
                'duration' => 120,
                'age_label' => 'C16',
                'tag' => 'HOT',
                'poster' => 'https://files.betacorp.vn/media/images/2026/03/26/anh-chup-man-hinh-2026-03-26-114032-114119-260326-54.png',
                'description' => 'Phí Phông, loài quỷ khát máu trong truyền thuyết dân gian của đồng bào miền núi gây ám ảnh bao đời nay. Phim xoay quanh Còn (Kiều Minh Tuấn) và Dương (Minh Anh), hai pháp sư tập sự lên núi cứu người mẹ đang bị lời nguyền Phí Phông đánh gục.',
                'release_date' => '2026-04-20',
                'language' => 'Tiếng Việt',
                'trailer' => 'https://www.youtube.com/embed/LDvCnwE6TtA',
                'details' => [
                    ['label' => 'Đạo diễn', 'value' => 'Đỗ Quốc Trung'],
                    ['label' => 'Diễn viên', 'value' => 'Kiều Minh Tuấn, Nina Nutthacha Padovan, Diệp Bảo Ngọc, Đoàn Minh Anh, NSƯT Hạnh Thuý,...'],
                    ['label' => 'Thể loại', 'value' => 'Kinh dị, Giật gân'],
                    ['label' => 'Thời lượng', 'value' => '120 phút'],
                    ['label' => 'Ngôn ngữ', 'value' => 'Tiếng Việt'],
                    ['label' => 'Ngày khởi chiếu', 'value' => '20/04/2026'],
                ],
                'is_active' => true,
            ],
            [
                'slug' => 'anh-hung',
                'section' => 'now-showing',
                'title' => 'Anh Hùng',
                'genre' => 'Tâm lý, Gia đình',
                'duration' => 122,
                'age_label' => 'C13',
                'tag' => 'HOT',
                'poster' => 'https://files.betacorp.vn/media/images/2026/03/31/400wx633h-113142-310326-81.jpg',
                'description' => 'Câu chuyện phim theo chân Hùng (Thái Hòa) - người cha đơn thân kiêm tài xế taxi và đồng nghiệp hãng xe là Tuấn (Võ Tấn Phát) bị cuốn vào một phi vụ lừa đảo từ thiện tiền tỉ trong khi sinh mạng cô con gái nhỏ của anh đang nằm gọn trong tay tử thần.',
                'release_date' => '2026-04-24',
                'language' => 'Tiếng Việt',
                'trailer' => 'https://www.youtube.com/embed/P74tpiZ8kuU',
                'details' => [
                    ['label' => 'Đạo diễn', 'value' => 'Võ Thạch Thảo'],
                    ['label' => 'Diễn viên', 'value' => 'Thái Hoà, Võ Tấn Phát, Đoàn Thế Vinh, Phương Thanh, Hồng Ánh, NSƯT Lê Thiện, Hoàng Minh Triết, Gia Tuệ...'],
                    ['label' => 'Thể loại', 'value' => 'Tâm lý, Gia đình'],
                    ['label' => 'Thời lượng', 'value' => '122 phút'],
                    ['label' => 'Ngôn ngữ', 'value' => 'Tiếng Việt'],
                    ['label' => 'Ngày khởi chiếu', 'value' => '24/04/2026'],
                ],
                'is_active' => true,
            ],
            [
                'slug' => 'dai-tiec-trang-mau-8',
                'section' => 'now-showing',
                'title' => 'Đại Tiệc Trăng Máu 8',
                'genre' => 'Hài hước, Kinh dị',
                'duration' => 130,
                'age_label' => 'C16',
                'tag' => 'HOT',
                'poster' => 'assets/img/poster-3.jpg',
                'description' => 'Đại Tiệc Trăng Máu 8 theo chân một vị đạo diễn hay bị coi thường trong dự án thử thách nhất đời ông: thực hiện một bộ phim dài 35 phút chỉ với một cú máy.',
                'release_date' => '2026-04-24',
                'language' => 'Tiếng Việt',
                'trailer' => 'https://www.youtube.com/embed/NZ9-wGErh4o',
                'details' => [
                    ['label' => 'Đạo diễn', 'value' => 'Phan Gia Nhật Linh'],
                    ['label' => 'Diễn viên', 'value' => 'Vân Sơn, Lê Khánh, Miu Lê, Liên Bỉnh Phát, Quốc Khánh, Quỳnh Lý, Lâm Thanh Mỹ, Quang Minh, Hứa Vĩ Văn, Hồng Ánh, NSƯT Đức Khuê, Charlie Nguyễn...'],
                    ['label' => 'Thể loại', 'value' => 'Hài hước, Kinh dị'],
                    ['label' => 'Thời lượng', 'value' => '130 phút'],
                    ['label' => 'Ngôn ngữ', 'value' => 'Tiếng Việt'],
                    ['label' => 'Ngày khởi chiếu', 'value' => '24/04/2026'],
                ],
                'is_active' => true,
            ],
            [
                'slug' => 'heo-nam-mong',
                'section' => 'now-showing',
                'title' => 'Heo Năm Móng',
                'genre' => 'Kinh dị',
                'duration' => 103,
                'age_label' => 'C18',
                'tag' => '',
                'poster' => 'assets/img/poster-4.png',
                'description' => 'Dựa trên truyền thuyết rùng rợn về "Cô Năm Hợi" và linh hồn bị mắc kẹt trong thân xác heo.',
                'release_date' => '2026-04-24',
                'language' => 'Tiếng Việt',
                'trailer' => 'https://www.youtube.com/embed/ShknvbpzZxg',
                'details' => [
                    ['label' => 'Đạo diễn', 'value' => 'Võ Thanh Hòa'],
                    ['label' => 'Diễn viên', 'value' => 'Võ Tấn Phát, Trần Ngọc Vàng, Nhật Ý, Thanh Thủy,..'],
                    ['label' => 'Thể loại', 'value' => 'Kinh dị'],
                    ['label' => 'Thời lượng', 'value' => '103 phút'],
                    ['label' => 'Ngôn ngữ', 'value' => 'Tiếng Việt'],
                    ['label' => 'Ngày khởi chiếu', 'value' => '24/04/2026'],
                ],
                'is_active' => true,
            ],
            [
                'slug' => 'trum-so',
                'section' => 'now-showing',
                'title' => 'Trùm Sò',
                'genre' => 'Hài hước',
                'duration' => 105,
                'age_label' => 'K',
                'tag' => '',
                'poster' => 'assets/img/poster-5.jpg',
                'description' => 'Ở Làng Sứa Đỏ - một ngôi làng nhỏ xa xôi heo hút, hạn hán triền miên, người dân ai cũng nghèo cũng khổ, chỉ riêng Trùm Sò là giàu nứt đố đổ vách.',
                'release_date' => '2026-04-24',
                'language' => 'Tiếng Việt',
                'trailer' => 'https://www.youtube.com/embed/QoKBpq_p61Q',
                'details' => [
                    ['label' => 'Đạo diễn', 'value' => 'Đỗ Đức Thịnh'],
                    ['label' => 'Diễn viên', 'value' => 'Đức Thịnh, Phương Nam, Mai Phương, Doãn Quốc Đam, Hoàng Tóc Dài,...'],
                    ['label' => 'Thể loại', 'value' => 'Hài hước'],
                    ['label' => 'Thời lượng', 'value' => '105 phút'],
                    ['label' => 'Ngôn ngữ', 'value' => 'Tiếng Việt'],
                    ['label' => 'Ngày khởi chiếu', 'value' => '24/04/2026'],
                ],
                'is_active' => true,
            ],
            [
                'slug' => 'hen-em-ngay-nhat-thuc',
                'section' => 'now-showing',
                'title' => 'Hẹn Em Ngày Nhật Thực',
                'genre' => 'Tâm lý, Gia đình',
                'duration' => 118,
                'age_label' => 'C16',
                'tag' => '',
                'poster' => 'assets/img/poster-6.jpg',
                'description' => 'Năm 1995, khi đang đứng trước một quyết định quan trọng của cuộc đời, Ân bất ngờ bị kéo trở lại quá khứ bởi những bức thư tình chưa từng trao tay.',
                'release_date' => '2026-03-30',
                'language' => 'Tiếng Việt',
                'trailer' => 'https://www.youtube.com/embed/xeuiol66BkA',
                'details' => [
                    ['label' => 'Đạo diễn', 'value' => 'Lê Thiện Viễn'],
                    ['label' => 'Diễn viên', 'value' => 'Đoàn Thiên Ân, Khương Lê, NSND Lê Khanh, Huỳnh Phương, Nguyên Thảo, NSND Kim Xuân, Thanh Sơn, Hứa Vĩ Văn, Lâm Vỹ Dạ, Hứa Minh Đạt.'],
                    ['label' => 'Thể loại', 'value' => 'Tâm lý, Gia đình'],
                    ['label' => 'Thời lượng', 'value' => '118 phút'],
                    ['label' => 'Ngôn ngữ', 'value' => 'Tiếng Việt'],
                    ['label' => 'Ngày khởi chiếu', 'value' => '30/03/2026'],
                ],
                'is_active' => true,
            ],
            [
                'slug' => 'cu-nhay-ky-dieu',
                'section' => 'now-showing',
                'title' => 'Cú Nhảy Kỳ Diệu',
                'genre' => 'Hoạt hình, Phiêu lưu',
                'duration' => 105,
                'age_label' => 'P',
                'tag' => '',
                'poster' => 'https://files.betacorp.vn/media/images/2026/02/26/anh-chup-man-hinh-2026-02-26-151006-151102-260226-84.png',
                'description' => 'Câu chuyện xoay quanh Mabel, nữ sinh đại học 19 tuổi với tình yêu mãnh liệt dành cho động vật, đã nắm bắt cơ hội sử dụng công nghệ cho phép ý thức “nhảy” vào một chú hải ly rô-bốt.',
                'release_date' => '2026-03-13',
                'language' => 'Tiếng Việt',
                'trailer' => 'https://www.youtube.com/embed/CHINiUp2L0g',
                'details' => [
                    ['label' => 'Đạo diễn', 'value' => 'Daniel Chong'],
                    ['label' => 'Diễn viên', 'value' => ''],
                    ['label' => 'Thể loại', 'value' => 'Hoạt hình, Phiêu lưu'],
                    ['label' => 'Thời lượng', 'value' => '105 phút'],
                    ['label' => 'Ngôn ngữ', 'value' => 'Tiếng Việt'],
                    ['label' => 'Ngày khởi chiếu', 'value' => '13/03/2026'],
                ],
                'is_active' => true,
            ],
            [
                'slug' => 'michael',
                'section' => 'now-showing',
                'title' => 'Michael',
                'genre' => 'Âm Nhạc',
                'duration' => 127,
                'age_label' => 'K',
                'tag' => '',
                'poster' => 'assets/img/poster-7.png',
                'description' => 'Michael là tác phẩm điện ảnh khắc họa cuộc đời và di sản của một trong những nghệ sĩ có ảnh hưởng nhất mà thế giới từng biết đến.',
                'release_date' => '2026-04-22',
                'language' => 'Tiếng Anh',
                'trailer' => 'https://www.youtube.com/embed/I7T5VK3zqbY',
                'details' => [
                    ['label' => 'Đạo diễn', 'value' => 'Antoine Fuqua'],
                    ['label' => 'Diễn viên', 'value' => 'Jaafar Jackson, Nia Long, Laura Harrier, Juliano Krue Valdi, cùng Miles Teller và Colman Domingo'],
                    ['label' => 'Thể loại', 'value' => 'Âm Nhạc'],
                    ['label' => 'Thời lượng', 'value' => '127 phút'],
                    ['label' => 'Ngôn ngữ', 'value' => 'Tiếng Anh'],
                    ['label' => 'Ngày khởi chiếu', 'value' => '22/04/2026'],
                ],
                'is_active' => true,
            ],
            [
                'slug' => 'phim-shin-cau-be-but-chi',
                'section' => 'now-showing',
                'title' => 'Phim Shin - Cậu Bé Bút Chì',
                'genre' => 'Hoạt hình, Gia đình',
                'duration' => 104,
                'age_label' => 'P',
                'tag' => '',
                'poster' => 'assets/img/poster-8.jpg',
                'description' => 'Bộ phim xoay quanh một vương quốc lơ lửng mang tên Rakuga, tồn tại nhờ nguồn năng lượng đến từ những nét vẽ của con người.',
                'release_date' => '2026-05-01',
                'language' => 'Tiếng Nhật',
                'trailer' => 'https://www.youtube.com/embed/KyyoTlt5VJo',
                'details' => [
                    ['label' => 'Đạo diễn', 'value' => 'Takahashi Wataru'],
                    ['label' => 'Diễn viên', 'value' => ''],
                    ['label' => 'Thể loại', 'value' => 'Hoạt hình, Gia đình'],
                    ['label' => 'Thời lượng', 'value' => '104 phút'],
                    ['label' => 'Ngôn ngữ', 'value' => 'Tiếng Nhật'],
                    ['label' => 'Ngày khởi chiếu', 'value' => '01/05/2026'],
                ],
                'is_active' => true,
            ],
        ];
    }
}
